name: tunnel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  google_sign_in: ^6.1.4
  flutter_svg: ^2.0.7
  flutter_signin_button: ^2.0.0
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.1.2
  flutter_chat_ui: ^1.6.8
  flutter_firebase_chat_core: ^1.5.0
  firebase_auth: ^4.6.3
  shared_preferences: ^2.2.0
  flutter_chat_types: ^3.6.1
  image_picker: ^1.0.0
  google_fonts: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  simple_animations: ^5.0.2
  bubble: ^1.2.1
  audioplayers: ^5.1.0
  flutter_local_notifications: ^15.1.0+1
  dio: ^5.3.2
  geolocator: ^10.0.0
  permission_handler: ^10.4.3
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcon~ios-marketing.png"

flutter:
  uses-material-design: true
  assets:
    - assets/